### ISSUE TITLE
Newline at end of paragraph / calling ParseAndRender multiple times

### ISSUE THREAD

**Issue by dgaus** [orf/HtmlToWord#5]
Hi, I'm having a slight problem with 0667ec68972e. If I do
```
html = "<p>paragraph</p><h1>header</h1>"
parser.ParseAndRender(html, word, document.ActiveWindow.Selection)
```
It works as expected. However, while building a document we call ParseAndRender several times, and if you do
```
parser.ParseAndRender('<p>paragraph</p>', word, document.ActiveWindow.Selection)
parser.ParseAndRender('<h1>header</h1>', word, document.ActiveWindow.Selection)
```
You can see that the paragraph ends up being turned into part of the header. Same thing happens if you add a `<ul>` instead of a `<hN>`. Now, we can add some logic to detect this case, but I thought maybe there's something better we can do? Let me know what you think, thanks!

**Comment by orf** [comment]
Hmm, I'm not sure how to handle this. Not including a newline at the end of the last paragraph being rendered makes sense if you are inserting content into an existing document (where a newline would look out of place), but if you are building a document from repeated ParseAndRender calls then not so much.

I can't really think of a nice way around this, if you can then let me know.

**Comment by dgaus** [comment]
Alright, will do, I'll close this for now, thanks!
